// src/auth/utils/normalize.util.ts

/**
 * Normalize IPv6-mapped IPv4 addresses to pure IPv4
 * Example: "::ffff:192.168.1.1" → "192.168.1.1"
 * Also handles malformed IPs with trailing characters or minor corruption.
 */

export function normalizeIp(ip: string | undefined | null): string | null {
  if (!ip) return null;

  // Handle IPv6-mapped IPv4 (common when behind proxies)
  if (ip.startsWith('::ffff:')) {
    // Extract the part after ::ffff:
    let result = ip.substring(7);
    // Remove any trailing colons, dots, or other invalid characters
    result = result.replace(/[:.\s]+$/, '');
    // Further sanitize: remove anything that's not a digit or dot
    result = result.replace(/[^0-9.]/g, '');
    return result;
  }

  // If it doesn't start with ::ffff:, it might be IPv4, IPv6, or corrupted.
  // If it starts like an IPv4 address (digits and dots), try to clean it up.
  // Use regex that checks the *beginning* of the string: ^\d+(\.\d+)*
  // This handles cases like '127.0.0.x' generated by maskIp.
  if (/^\d+(\.\d+)*/.test(ip)) { // Starts with digits and dots (e.g., 127, 127.0, 127.0.0, 127.0.0.x)
    // Remove anything that's not a digit or dot
    let sanitized = ip.replace(/[^0-9.]/g, '');
    // Remove trailing dots
    sanitized = sanitized.replace(/[.]+$/, '');
    // Basic check to see if it looks like a plausible IPv4 segment structure after sanitization
    const segments = sanitized.split('.');
    if (segments.length > 0 && segments.length <= 4 && segments.every(seg => seg.length > 0 && seg.length <= 3 && !seg.startsWith('0') || seg === '0')) {
        // Reconstruct a plausible IPv4
        return segments.join('.');
    } else {
        // Return the sanitized version, ensuring no trailing dots.
        return sanitized.replace(/[.]+$/, '');
    }
  }

  // For other formats (IPv6, or completely invalid-looking), return the input.
  // isValidIP will handle the final validation.
  return ip;
}

/**
 * Truncate user-agent to prevent DB bloat
 * Max length: 200 chars (adjustable)
 */
export function normalizeUserAgent(
  ua: string | undefined | null,
): string | null {
  if (!ua) return null;

  // Strip leading/trailing whitespace
  const trimmed = ua.trim();

  // Truncate if too long
  return trimmed.length > 200 ? trimmed.substring(0, 200) : trimmed;
}
